language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  # Rubinius in 1.8 mode on Travis does not work. It complains about st_data_t etc in Xcodeproj.
  #- rbx-18mode
  - rbx-19mode
install: NOEXEC=skip rake travis:setup
script: RUBYOPT=-Ku bundle exec rake spec
