osx_image: xcode7.3
language: objective-c
cache: bundler
rvm:
  # OS X 10.9.5-10.10.0 (2.0.0-p481)
  - system
  # OS X 10.9.3-10.9.4
  - 2.0.0-p451
  # OS X 10.9.0-10.9.2
  # TODO: currently unavailable: https://github.com/travis-ci/travis-ci/issues/2918
  # - 2.0.0-p247
  - 2.3.1

branches:
  only:
    - master
    - /.+-stable$/

before_install:
  # There is a bug in travis. When using system ruby, bundler is not
  # installed and causes the default install action to fail.
  - sudo gem install bundler
  # RubyGems 2.0.14 isn't a fun time on 2.0.0p645
  - if [ "$(ruby -v | cut -d ' ' -f2)" = "2.0.0p645" ]; then sudo gem update --system; fi

before_script:
  - bundle exec pod repo update --silent
  - bundle exec pod env

script:
  - bundle exec rake
  - bundle exec danger

addons:
 code_climate:
   repo_token: 501acd9bc61d80ef6119b69ab42c52fa66cefddcc6724a1e93a79c3d3e32bf55
