version: 2.0
jobs:
  build:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - run:
          name: Set Ruby Version
          command:  echo "2.4" > ~/.ruby-version
      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Setup Dependencies
          command: |
            function bundle_env () {
              bundle env
            }
            trap bundle_env ERR

            bundle check || bundle install --path .bundle
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - ".bundle"
      - run:
          name: Setup Git
          command: |
            git config --global user.email "tests@cocoapods.org"
            git config --global user.name "CocoaPods Tests"
      - run: bundle exec pod env
      - run:
          name: Run Examples
          command: bundle exec rake spec:all
          environment:
           COCOAPODS_CI_TASKS: EXAMPLES
           COCOAPODS_SPEC_REPO: https://cdn.cocoapods.org/
